### PR TITLE
Add policy attachment properties to user resource

### LINKED ISSUE #74: Add has_policies? and has_attached_policies? to user.
For recommendation 1.16.  See
```
aws iam list-attached-user-policies --user-name <iam_user>
```

in the CIS benchmark.

### PR DESCRIPTION
**Pull request by chris-redekop**
Adding `has_policies?` and `has_attached_policies?`.   Fixes #74.

### CODE REVIEW

**Review by aduric — APPROVED** [review]

**Review by Stiffni — APPROVED** [review]

**Review by clintoncwolfe — CHANGES_REQUESTED** [review]
I'd like to put this on hold until #121 and #125 are in place.

**Comment by chris-redekop** [comment]
Sounds good, @clintoncwolfe .

While resource creation is on hold, I'll take a look and #121 and #125.  Is there any other work that we can pickup?

**Comment by clintoncwolfe** [comment]
@chris-redekop - Two docs issues, #102 and #103 would be great to get covered.

**Comment by clintoncwolfe** [comment]
Well, #121 and #125 together altered how aws_iam_user works quite a bit.  Would you like me to work on this branch a bit to get it across the finish line?

**Comment by chris-redekop** [comment]
Thanks for the offer, @clintoncwolfe .  I actually think reworking this PR would be a good exercise for @Rugbyte and me, to help us better understand your improvements.

If this is blocking other work, please do go ahead and finish it up; otherwise, @Rugbyte and I will get it ready for review!

**Comment by rx294** [comment]
Hello @chris-redekop @clintoncwolfe looks like  #121 and #125 are merged. Is there anything else holding up this PR? Please let me know if I can help. 

I am working with @aaronlippold to complete the CIS AWS profile and would like to have has_policies? and has_attached_policies? properties for CIS 1.16

**Pull request closed without merging**
