### PR TITLE
Updating aws_iam_user with exists? function. 

### PR DESCRIPTION
**Pull request by NickRycar**
Pretty simple update. Adds an exists? function to the aws_iam_user resource, and associated unit tests. Successfully tested against my AWS user.

Signed-off-by: Nick Rycar <rycar@chef.io>

### CODE REVIEW

**Comment by ChefRycar** [comment]
Solves #114

**Review by clintoncwolfe — CHANGES_REQUESTED** [review]
Thanks @ChefRycar!  Code looks good, and unit and integration tests pass.  Rubocop is unhappy (though #117 would render that irrelevant).  You can either wait for #117 to be resolved, or you can add 
` # rubocop:disable Metrics/ClassLength` to the end of `test/unit/resources/aws_iam_user_test.rb:6`

Thanks!

**Comment by ChefRycar** [comment]
Thanks for the feedback, @clintoncwolfe !

Looks like rubocop wanted me to throw it at or above the class to properly catch it, but I think it's behaving itself now. Let me know if it needs any further updates.

**Review by clintoncwolfe — APPROVED** [review]

**Review by chris-rock — APPROVED** [review]
Thank you @ChefRycar

**Pull request merged**
