### PR TITLE
Add AWS_SESSION_TOKEN

### PR DESCRIPTION
**Pull request by chris-redekop**
This addresses issue #106 .

@aduric @Stiffni @Rugbyte FYI.

### CODE REVIEW

**Comment by jerryaldrichiii** [comment]
:+1: Looks good to me, I'm not sure how to create/use/test a session token though.

**Comment by chris-redekop** [comment]
I think you can use the `get-session-token` command to create a token.  See http://docs.aws.amazon.com/cli/latest/reference/sts/get-session-token.html

Also, a here is some background info on the env var: http://docs.amazonaws.cn/en_us/cli/latest/userguide/cli-environment.html

**Review by clintoncwolfe — APPROVED** [review]
This works, with a UX caveat.  If you test any IAM resource, the user that created the session token must have MFA enabled _and_ must have passed the MFA token when creating the session token, eg:
```
# With cwolfe's normal profile loaded in to env
aws sts get-session-token --serial-number arn:aws:iam::<mfa_device_number>:mfa/cwolfe --token-code <current_mfa_value>
```

If the session token was not created with MFA data, then you get a blunt 
```
The security token included in the request is invalid
```
message.  I don't think we can detect that distinction though.

**Review by clintoncwolfe — CHANGES_REQUESTED** [review]
Actually, I see we document the ENV variables in the README.md .  Could you update the README accordingly?  Thanks!

**Comment by chris-redekop** [comment]
Thanks, @clintoncwolfe .  README updated.

I agree, I don't think we can detect an under-privileged token without trying to authenticate.

The use case that I imagine targets a control author who already uses tokens for AWS authentication, and wants to (or must) authenticate the same way with inspec-aws.  In this use case, the author is already as familiar with session tokens as we are with secret keys.  And in *that* case, I think AWS's standard messages are OK.

?

**Comment by clintoncwolfe** [comment]
@chris-redekop - Looks OK, but I think you missed the sign-off on that last commit.  Could you add it and re-push?

**Comment by chris-redekop** [comment]
Sorry about that.  Done!

**Review by clintoncwolfe — APPROVED** [review]

**Review by chris-rock — APPROVED** [review]
Thank you @chris-redekop

**Pull request merged**
